budget/urls.py
from django.urls import path

from budget.views import (
    BudgetCreateView,
    BudgetDeleteView,
    BudgetDetailView,
    BudgetListView,
    BudgetUpdateView,
)

urlpatterns = [
    path("", BudgetListView.as_view(), name="budget_list"),
    path("<int:pk>/delete/", BudgetDeleteView.as_view(), name="delete_budget"),
    path("create/", BudgetCreateView.as_view(), name="create_budget"),
    path("<int:pk>/complete/", BudgetUpdateView.as_view(), name="update_budget"),
    path("<int:pk>/", BudgetDetailView.as_view(), name="budget_detail")
    
]

guestlist/urls.py
from django.urls import path

from guestlist.views import (
    GuestListDeleteView,
    GuestListCreateView,
    GuestListListView,
    GuestListUpdateView
)

urlpatterns = [
    path("", GuestListListView.as_view(), name="guest_list"),
    path("<int:pk>/delete/", GuestListDeleteView.as_view(), name="delete_guest"),
    path("create/", GuestListCreateView.as_view(), name="create_guest"),
    path("<int:pk>/complete/", GuestListUpdateView.as_view(), name="complete_rsvp")
    
]

planner/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("budget/", include("budget.urls")),
    path("accounts/", include("accounts.urls")),
    path("guestlist/", include("guestlist.urls")),
    path("weddings/", include("weddings.urls")),
    path('admin/', admin.site.urls),
    path("", RedirectView.as_view(url=reverse_lazy("wedding_list")), name="home",)
]

guestlist/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.

class GuestList(models.Model):
    name = models.CharField(max_length=200)
    plus = models.PositiveSmallIntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(5)])
    rsvp = models.BooleanField(default=False)
    
    def __str__(self):
        return self.name

guestlist/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from guestlist.models import GuestList
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

class GuestListListView(LoginRequiredMixin, ListView):
    model = GuestList
    template_name = "guestlist/list.html"

class GuestListDeleteView(LoginRequiredMixin, DeleteView):
    model = GuestList
    template_name = "guestlist/delete.html"
    success_url = reverse_lazy("guest_list")

class GuestListCreateView(LoginRequiredMixin, CreateView):
    model = GuestList
    template_name = "guestlist/create.html"
    fields = ["name", "plus", "rsvp"]

    def form_valid(self, form):
        guestlist = form.save(commit=False)
        guestlist.save()
        form.save()
        return redirect("guest_list")

class GuestListUpdateView(LoginRequiredMixin, UpdateView):
    model = GuestList
    template_name = "guestlist/list.html"
    fields = ["rsvp"]
    success_url = reverse_lazy("guest_list")

    def form_valid(self, form):
        guestlist = form.save(commit=False)
        guestlist.save()
        form.save()
        return redirect("guest_list")

guestlist/templates/guestlist/create.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<main>
    <div>
        <h1>Add a guest</h1>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="button">Add</button>
        </form>
    </div>
</main>


{% endblock content %}

guestlist/templates/guestlist/delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<main>
    <div>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="button">Delete</button>
    </form>
    </div>
</main>

{% endblock content %}

guestlist/templates/guestlist/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<main>
    <div>
        <h1>Guest List</h1>
        <p>
            <a href="{% url 'create_guest' %}">Add a new guest</a>
        </p>
        {% if guestlist_list|length > 0 %}
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Plus</th>
                    <th>RSVP</th>
                </tr>
                
                {% for guest in guestlist_list %}
                <tr>
                    <td>{{ guest.name }}</a></td>
                    <td>{{ guest.plus }}</td>
                    <td>{% if guest.rsvp is True %}
                        Yes
                        {% else %}
                        <form method="post" action ="{% url 'complete_rsvp' guest.id %}">
                            {% csrf_token %}
                            <input type="hidden" name="rsvp" value="True">
                            <button>RSVP</button>
                        </form>
                    </td>
                    {% endif %}
                    
                    <td>
                        <a href="{% url 'delete_guest' guest.id %}">
                            <button class="button">Delete</button>
                        </a>
                            
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </thead>
        </table>
        {% endif %}
    </div>
</main>

{% endblock content %}